export { PaginaPrincipal } from './Principal/PaginaPrincipal'
export { PaginaRegistro } from './Registro/PaginaRegistro'
export { PaginaPausa } from './Pausa/PaginaPausa'
export { PaginaRitmo } from './Ritmo/PaginaRitmo'
export { PaginaConfig } from './Config/PaginaConfig'
